"""Build site/sitemap.xml from the pages that actually exist under site/.

What goes in:
  * root pages (site/*.html) — index.html is listed as the site root "/";
  * generated deck pages      — site/decks/<slug>/index.html → /decks/<slug>/;
  * the articles index        — site/articles/index.html     → /articles/;
  * published articles        — site/articles/<slug>/index.html → /articles/<slug>/
    (only slugs listed in site/data/articles.json, so a local --include-drafts
    build never leaks a draft into the sitemap).

What stays out: templates that are copied into subfolders (articles.html,
article.html — their real URLs are /articles/…), the 404 page, the dev-only
deck_tests.html, anything under concepts/ partials/ data/ assets/, and any page
that carries <meta name="robots" content="noindex">.

<lastmod> is only written where we know a real date: an article's publication
date, and the newest of those for the articles index. File modification times
would change on every CI checkout and make the sitemap churn daily.

The output is sorted and deterministic, and the file is only rewritten when
its content changes, so running this repeatedly produces no diff.

Run after adding or removing pages (and after generate_deck_pages.py /
build_articles.py have run):
    python scripts/build_sitemap.py           # write site/sitemap.xml
    python scripts/build_sitemap.py --check   # exit 1 if it is out of date
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from xml.sax.saxutils import escape

REPO_ROOT = Path(__file__).resolve().parent.parent
SITE_DIR = REPO_ROOT / "site"
SITE_URL = "https://atlas-conquest.com"

SKIP_DIRS = {"concepts", "partials", "data", "assets"}
EXCLUDE_ROOT_PAGES = {
    "404.html",          # served by GitHub Pages for missing URLs, never linked
    "deck_tests.html",   # in-browser test harness
    "articles.html",     # template → /articles/
    "article.html",      # template → /articles/<slug>/
}

_NOINDEX_RE = re.compile(
    r'<meta\s+name=["\']robots["\']\s+content=["\'][^"\']*noindex', re.IGNORECASE
)


def _noindex(path: Path) -> bool:
    return bool(_NOINDEX_RE.search(path.read_text(encoding="utf-8", errors="replace")))


def _published_articles(site_dir: Path) -> dict[str, str] | None:
    """slug → ISO date from data/articles.json, or None when there's no index."""
    index = site_dir / "data" / "articles.json"
    if not index.exists():
        return None
    data = json.loads(index.read_text(encoding="utf-8"))
    return {a["slug"]: a.get("date", "") for a in data.get("articles", []) if a.get("slug")}


def collect_urls(site_dir: Path = SITE_DIR) -> list[tuple[str, str | None]]:
    """Return [(absolute URL, lastmod or None), …] in sitemap order."""
    entries: list[tuple[str, str | None]] = []

    # Root pages: home first, then alphabetical.
    root_pages = sorted(
        p for p in site_dir.glob("*.html")
        if p.name not in EXCLUDE_ROOT_PAGES and not _noindex(p)
    )
    root_pages.sort(key=lambda p: (p.name != "index.html", p.name))
    for page in root_pages:
        path = "/" if page.name == "index.html" else f"/{page.name}"
        entries.append((SITE_URL + path, None))

    # Generated deck pages.
    for page in sorted((site_dir / "decks").glob("*/index.html")):
        if not _noindex(page):
            entries.append((f"{SITE_URL}/decks/{page.parent.name}/", None))

    # Articles: the index, then each published article (newest first).
    published = _published_articles(site_dir)
    articles: list[tuple[str, str | None]] = []
    for page in sorted((site_dir / "articles").glob("*/index.html")):
        slug = page.parent.name
        if published is not None and slug not in published:
            continue
        if _noindex(page):
            continue
        date = (published or {}).get(slug) or None
        articles.append((f"{SITE_URL}/articles/{slug}/", date))
    articles.sort(key=lambda e: (e[1] or "", e[0]), reverse=True)
    articles_index = site_dir / "articles" / "index.html"
    if articles_index.exists() and not _noindex(articles_index):
        newest = max((d for _, d in articles if d), default=None)
        entries.append((f"{SITE_URL}/articles/", newest))
    entries.extend(articles)
    return entries


def render_sitemap(entries: list[tuple[str, str | None]]) -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by scripts/build_sitemap.py from the pages under site/. Do not edit. -->",
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for url, lastmod in entries:
        lines.append("  <url>")
        lines.append(f"    <loc>{escape(url)}</loc>")
        if lastmod:
            lines.append(f"    <lastmod>{escape(lastmod)}</lastmod>")
        lines.append("  </url>")
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def build(site_dir: Path = SITE_DIR, check_only: bool = False) -> int:
    out = site_dir / "sitemap.xml"
    xml = render_sitemap(collect_urls(site_dir))
    current = out.read_text(encoding="utf-8") if out.exists() else None
    if current == xml:
        print(f"sitemap.xml up to date ({xml.count('<url>')} URLs)")
        return 0
    if check_only:
        print("sitemap.xml is out of date — run `python scripts/build_sitemap.py`", file=sys.stderr)
        return 1
    out.write_text(xml, encoding="utf-8")
    print(f"Wrote sitemap.xml ({xml.count('<url>')} URLs)")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build site/sitemap.xml from the site's pages.")
    parser.add_argument("--check", action="store_true",
                        help="Don't write; exit 1 if sitemap.xml is out of date.")
    args = parser.parse_args(argv)
    return build(check_only=args.check)


if __name__ == "__main__":
    sys.exit(main())
